default: &default
  adapter: mysql2
  charset: utf8mb4
  collation: utf8mb4_bin
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DB_USERNAME") { } %>
  password: <%= ENV.fetch("DB_PASSWORD") { }%>
  host: <%= ENV.fetch("DB_HOST") { } %>
  port: <%= ENV.fetch("DB_PORT") { } %>
  timeout: 5000

development:
  <<: *default
  database: <%= ENV.fetch("DB_NAME") { } %>
